### PR TITLE
Adding myself (Max Gautier) as org member

### PR DESCRIPTION
**Pull request by VannTen**

### CODE REVIEW

**Comment by goern** [comment]
oh... @VannTen maybe add yourself to thoth team ;)

**Comment by VannTen** [comment]
I am already in it I think ? Unless there is another than thoth-station
org ?

**Comment by goern** [comment]
ah, right. I meant https://github.com/AICoE/common/blob/main/github-config.yaml#L751 ;)

**Comment by VannTen** [comment]
> ah, right. I meant https://github.com/AICoE/common/blob/main/github-config.yaml#L751 ;)
Ah !. Yeah will do. Is that doing anything though then ?

-- 
Max Gautier

**Pull request merged**
