### PR TITLE
Add missing triage labels

### PR DESCRIPTION
**Pull request by codificat**
The AICoE repos are missing a couple of labels that are used for issue triage: `needs-triage` and `triage/accepted`.

Example issues showing that gap in action include https://github.com/AICoE/manage-dependencies-tutorial/issues/25#issuecomment-966223937, https://github.com/AICoE/sefkhet-abwy/issues/184#issuecomment-966444744, https://github.com/AICoE/aicoe-ci/issues/153#issuecomment-979304089

This PR adds these two labels.

### CODE REVIEW

**Review by harshad16 — APPROVED** [review]
lgtm
thanks :100:

**Comment by codificat** [comment]
Updated to only add the `triage/accepted` label.

The `needs-triage` label is meant to be managed by a dedicated prow plugin which is currently not configured to act on any of the repos in the AICoE github org (ref https://github.com/thoth-station/thoth-application/issues/2359#issuecomment-1042832262 and https://github.com/thoth-station/thoth-application/blob/620b649dc4c67c8cb9f926feb3c6b53ccd355e64/prow/overlays/smaug/plugins.yaml#L45)

**Comment by codificat** [comment]
This needs an /lgtm from @goern or @tumido 

Note that I also included a fix for the path change in the `label_sync` image (same as https://github.com/open-services-group/community/pull/84, ref https://github.com/kubernetes/test-infra/blob/198fd8ef3d2441af01a0fad802ec9809b162e599/prow/ANNOUNCEMENTS.md?plain=1#L195)

**Pull request merged**
