### PR TITLE
:arrow_up: adding a group for varangian contributors

### PR DESCRIPTION
**Pull request by goern**
Signed-off-by: Christoph Görn <goern@redhat.com>

### CODE REVIEW

**Comment by goern** [comment]
I think the CI error "{"component":"peribolos","file":"k8s.io/test-infra/prow/cmd/peribolos/main.go:188","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure AICoE teams: failed to update Varangian-admins members: failed to list varangian-admins(Varangian-admins) members: return code not 2XX: 404 Not Found","severity":"fatal","time":"2022-06-17T10:06:14Z"}" is ok, as I renamed one team.

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve

**Review by saurabhpujar — APPROVED** [review]
LGTM

**Pull request merged**
