### PR TITLE
Create repos for tutorials

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

4 repos for 4 new tutorials:

Example 1 - manage-dependencies-tutorial
Example 2 - recommend-base-image-tutorial
Example 3 - overlays-for-ai-pipeline-tutorial
Example 4 - receive-feedback-on-deployment-tutorial

Related-To: https://github.com/thoth-station/core/issues/308

### CODE REVIEW

**Review by tumido — APPROVED** [review]
/approve
/lgtm

**Comment by tumido** [comment]
CI not working, I'll apply the config manually. Merging

**Comment by pacospace** [comment]
> CI not working, I'll apply the config manually. Merging

How much does it take usually to create repos?

**Comment by goern** [comment]
`peribolos` just finished running from my local host.

@pacospace pls chk

**Comment by pacospace** [comment]
> `peribolos` just finished running from my local host.
> 
> @pacospace pls chk

All available!! Thanks!

**Pull request merged**
