### PR TITLE
Add readme + fix labels job

### PR DESCRIPTION
**Pull request by tumido**
- Adds a readme linking to Prow and other docs 
- renames the postsublit jobs to be unique for this org, so we can generate a badge for it.
- fix labels job spec to use the default entrypoint

### CODE REVIEW

**Comment by goern** [comment]
/approve
/hold

shall we change the context of the peribolos jobs?

**Comment by tumido** [comment]
> shall we change the context of the peribolos jobs?

@goern 

I've added `context` to the postsubmit jobs to match the presubmit. I think this is fine as it is. The `name` is used in the prow deck UI, while context is used on GitHub...

**Pull request merged**
